Repository apache/mynewt-core, pull requests merged in 2018-03, with the labels that each got.

#870 nimble/phy: Fix receiver configuration on late RX
  hw/drivers/nimble/nrf52/src/ble_phy.c
Labels: bug

#871 nimble/ll: Allow setting scan rsp data before configuring advertising
  net/nimble/controller/src/ble_ll_adv.c
Labels: enhancement

#882 libc: Add support for float in printf
  libc/baselibc/src/tinyprintf.c
Labels: enhancement

#888 kernel/os: Make sure correct stack aligment
  kernel/os/include/os/os_task.h
  kernel/os/src/os.c
  net/nimble/controller/src/ble_ll.c
  net/nimble/host/mesh/src/adv.c
  net/nimble/host/mesh/src/shell.c
Labels: bug, documentation

#866 nimble/dtm: Couple of improvements helping in RF testing.
  net/nimble/controller/src/ble_ll_dtm.c
Labels: enhancement

#881 Lps33hw
  hw/drivers/sensors/lps33hw/include/lps33hw/lps33hw.h
  hw/drivers/sensors/lps33hw/pkg.yml
  hw/drivers/sensors/lps33hw/src/lps33hw.c
  hw/drivers/sensors/lps33hw/src/lps33hw_priv.h
  hw/drivers/sensors/lps33hw/src/lps33hw_shell.c
  hw/drivers/sensors/lps33hw/syscfg.yml
  hw/sensor/creator/src/sensor_creator.c
  hw/sensor/creator/syscfg.yml
Labels: feature

#883 nimble/ll: Improve extended scan/connect when host request both PHYs to be used
  net/nimble/controller/src/ble_ll_scan.c
Labels: bug

#918 hw/mcu/nordic: Fixes in hal_gpio
  hw/mcu/nordic/nrf51xxx/src/hal_gpio.c
  hw/mcu/nordic/nrf52xxx/src/hal_gpio.c
Labels: bug

#892 sensors:bma253: Add config for stream/poll read
  hw/drivers/sensors/bma253/include/bma253/bma253.h
  hw/drivers/sensors/bma253/src/bma253.c
  hw/sensor/creator/src/sensor_creator.c
Labels: enhancement

#926 Add Driver for LIS2DW12
  hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
  hw/drivers/sensors/lis2dw12/pkg.yml
  hw/drivers/sensors/lis2dw12/src/lis2dw12.c
  hw/drivers/sensors/lis2dw12/src/lis2dw12_priv.h
  hw/drivers/sensors/lis2dw12/syscfg.yml
  hw/sensor/creator/src/sensor_creator.c
  hw/sensor/creator/syscfg.yml
Labels: feature

#931 Adding support for SPI_2 for nrf52
  hw/mcu/nordic/nrf52xxx/src/hal_spi.c
  hw/mcu/nordic/nrf52xxx/syscfg.yml
Labels: enhancement

#951 hw/nrfxx/adc: Fix handling ADC configuration
  hw/bsp/ada_feather_nrf52/src/hal_bsp.c
  hw/bsp/arduino_primo_nrf52/src/hal_bsp.c
  hw/bsp/bmd200/src/hal_bsp.c
  hw/bsp/bmd300eval/src/hal_bsp.c
  hw/bsp/calliope_mini/src/hal_bsp.c
  hw/bsp/dwm1001-dev/src/hal_bsp.c
  hw/bsp/nina-b1/src/hal_bsp.c
  hw/bsp/nrf51-arduino_101/src/hal_bsp.c
  hw/bsp/nrf51-blenano/src/hal_bsp.c
  hw/bsp/nrf51dk-16kbram/src/hal_bsp.c
  hw/bsp/nrf51dk/src/hal_bsp.c
  hw/bsp/nrf52-thingy/src/hal_bsp.c
  hw/bsp/nrf52840pdk/src/hal_bsp.c
  hw/bsp/nrf52dk/src/hal_bsp.c
  hw/bsp/puckjs/src/hal_bsp.c
  hw/bsp/rb-blend2/src/hal_bsp.c
  hw/bsp/rb-nano2/src/hal_bsp.c
  hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
  hw/bsp/telee02/src/hal_bsp.c
  hw/bsp/vbluno51/src/hal_bsp.c
  hw/bsp/vbluno52/src/hal_bsp.c
  hw/drivers/adc/adc_nrf51/include/adc_nrf51/adc_nrf51.h
  hw/drivers/adc/adc_nrf51/src/adc_nrf51.c
  hw/drivers/adc/adc_nrf52/include/adc_nrf52/adc_nrf52.h
  hw/drivers/adc/adc_nrf52/src/adc_nrf52.c
Labels: bug

#889 implementation of common button events
  hw/util/button/include/button/button.h
  hw/util/button/pkg.yml
  hw/util/button/src/button.c
  hw/util/button/syscfg.yml
Labels: feature

#960 lis2dw12: Add set_config function
  hw/drivers/sensors/lis2dw12/src/lis2dw12.c
Labels: enhancement
