Repository apache/mynewt-core, pull requests merged in 2024-09, with the labels that each got.

#3302 hw/bsp: pca10059 add readme.md
  hw/bsp/nordic_pca10059/readme.md
Labels: Nordic, BSP, size/s

#3303 hw/bsp: pca10059 update readme.md
  hw/bsp/nordic_pca10059/readme.md
Labels: Nordic, BSP, size/s

#3304 ci: Fix style check
  .github/check_style.py
Labels: size/xs

#3305 drivers/i2s: Fix missing dependency
  hw/drivers/i2s/pkg.yml
Labels: size/xs

#3306 uncrustify: Update configuration
  uncrustify.cfg
Labels: size/s

#3307 hw/drivers/bme280: Fix writes to I2C
  hw/drivers/sensors/bme280/include/bme280/bme280.h
  hw/drivers/sensors/bme280/src/bme280.c
Labels: size/s

#3308 fs/fcb: Coverity fix
  fs/fcb/src/fcb_getnext.c
Labels: size/s

#3309 documentation/sphinx: Fix formatting errors in `.rst` files
  docs/os/modules/baselibc.rst
  docs/os/modules/hal/hal_i2c/hal_i2c.rst
  docs/os/tutorials/STM32F303.rst
  docs/os/tutorials/pin-wheel-mods.rst
Labels: size/xs

#3311 docs: Fix the layout in multiple .rst files for the PDF output
  docs/os/modules/devmgmt/customize_newtmgr.rst
  docs/os/modules/devmgmt/oicmgr.rst
  docs/os/modules/imgmgr/imgmgr.rst
  docs/os/modules/imgmgr/imgmgr_module_init.rst
Labels: size/l
