Repository apache/mynewt-core, pull requests merged in 2024-10, with the labels that each got.

#3313 hw/drivers/i2s: Fix I2S driver for STM32F1 family
  hw/drivers/i2s/i2s_stm32f1/src/i2s_stm32f1.c
Labels: size/xs

#3314 mcu/stm32: Fix clock configuration for non STM32F4xx
  hw/mcu/stm/stm32f4xx/src/clock_stm32f4xx.c
Labels: STM, size/xs

#3317 libc: Add newlib-nano printf float support
  libc/nano/pkg.yml
Labels: size/xs

#3315 lvgl: Add driver for ft6x36 touch screen
  hw/drivers/display/lvgl/indev/ft6x36/pkg.yml
  hw/drivers/display/lvgl/indev/ft6x36/src/ft6x36.c
  hw/drivers/display/lvgl/indev/ft6x36/syscfg.yml
  hw/drivers/display/lvgl/pkg.yml
  hw/drivers/display/lvgl/syscfg.yml
Labels: size/m

#3316 lvgl: Add IPS parameters to ILI9341 driver
  hw/drivers/display/lvgl/tft/ili9341/src/ili9341.c
  hw/drivers/display/lvgl/tft/ili9341/syscfg.yml
Labels: size/s

#3319 sys/log: Fix build with LOG_STORAGE_INFO enabled
  sys/log/full/src/log_shell.c
Labels: size/xs

#3320 baselibc: Add option to enable extra debugging for malloc/free
  libc/baselibc/pkg.yml
  libc/baselibc/syscfg.yml
Labels: size/xs

#3322 kernel: Fix builds for C++
  kernel/os/include/os/arch/mips/os/os_arch.h
  kernel/os/include/os/arch/pic32/os/os_arch.h
  kernel/os/include/os/os_callout.h
  kernel/os/include/os/os_cputime.h
  kernel/os/include/os/os_trace_api.h
  sys/console/full/include/console/history.h
  sys/coredump/include/coredump/coredump.h
  sys/fault/include/fault/fault.h
  sys/flash_map/include/flash_map/flash_map.h
  sys/log/modlog/include/modlog/modlog.h
  sys/mfg/include/mfg/mfg.h
Labels: size/s

#3323 sys/config: Fix default CONFIG_FLOAT_SUPPORT value
  sys/config/syscfg.yml
Labels: size/xs

#3326 crypto/mbedtls: Upgrade to v2.28.9
  crypto/mbedtls/pkg.yml
Labels: size/xs

#3329 kernel/os_sanity: Remove double function typedef
  kernel/os/include/os/os_sanity.h
Labels: size/xs

#3328 mcu/nordic: Update NRFX to version 3.8.0
  hw/mcu/nordic/pkg.yml
Labels: Nordic, size/xs

#3321 DA1469x: Clock time shifts on reboots
  hw/mcu/dialog/da1469x/include/mcu/da1469x_clock.h
  hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h
  hw/mcu/dialog/da1469x/include/mcu/da1469x_lpclk.h
  hw/mcu/dialog/da1469x/src/da1469x_clock.c
  hw/mcu/dialog/da1469x/src/da1469x_lpclk.c
  hw/mcu/dialog/da1469x/src/hal_os_tick.c
  hw/mcu/dialog/da1469x/src/hal_system.c
  hw/mcu/dialog/da1469x/syscfg.yml
Labels: size/m

#3325 sys/queue: Update to version from FreeBSD 14.1
  sys/sys/include/sys/queue.h
Labels: size/l

#3331 baselibc: Don't use -umain for native build
  libc/baselibc/pkg.yml
Labels: size/xs

#3330 sys/shell: Fix the Tasks table header row
  sys/shell/src/shell_os.c
Labels: size/xs

#3334 sys/queue: Add definition of __containerof
  sys/sys/include/sys/queue.h
Labels: size/xs

#3333 ci: Only download required repositories
  .github/project_build_all_apps.yml
  .github/project_build_cc_target.yml
  .github/project_newt_test_all.yml
  .github/workflows/build_all_apps.yml
  .github/workflows/build_cc_target.yml
  .github/workflows/newt_test_all.yml
Labels: CI, size/m
