Repository apache/mynewt-core, pull requests merged in 2024-11, with the labels that each got.

#3338 kernel/os: Increase mutex test timeout
  kernel/os/selftest/src/testcases/os_mutex_test_basic.c
  kernel/os/selftest/src/testcases/os_mutex_test_case_1.c
  kernel/os/selftest/src/testcases/os_mutex_test_case_2.c
Labels: size/xs

#3324 sys/config: Add option to skip dup check when saving values
  sys/config/src/config_store.c
  sys/config/syscfg.yml
Labels: size/s

#3339 hw/mcu/dialog: GPIO configuration with single value
  hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h
  hw/mcu/dialog/da1469x/src/hal_gpio.c
Labels: size/s

#3340 hw/mcu/samd21xx: Update repo version to 1.13.0
  hw/mcu/atmel/samd21xx/ext/pkg.yml
Labels: size/xs

#3343 Prepare for Apache Mynewt 1.13.0 release
  RELEASE_NOTES.md
  repository.yml
Labels: size/s

#3346 Apache Mynewt 1.13.0 release
  repository.yml
Labels: size/xs

#3345 hw/mcu/nordic: FIX GPIO HAL for non secure code
  hw/mcu/nordic/nrf_common/src/hal_gpio.c
Labels: Nordic, size/s

#3348 sys/log: Zero-initialize log_offset struct
  sys/log/full/src/log.c
  sys/log/full/src/log_fcb.c
  sys/log/full/src/log_fcb2.c
Labels: size/xs

#3347 crypto: tinycrypt: Fix spurious uninitialized array error
  crypto/tinycrypt/pkg.yml
Labels: size/xs

#3351 fs/fatfs: Add modlog to fatfs
  fs/fatfs/src/mynewt_glue.c
  fs/fatfs/syscfg.yml
Labels: size/s
