Repository apache/mynewt-core, pull requests merged in 2025-05, with the labels that each got.

#3417 sys/log: Simplify module coloring scheme
  sys/log/full/src/log_console.c
Labels: size/s

#3414 log_fcb: optimize log_fcb_copy
  sys/log/full/src/log_fcb.c
Labels: size/s

#3415 hal/spi: Add missing hal_spi_init_hw function
  hw/mcu/stm/stm32_common/src/hal_spi.c
Labels: STM, size/s

#3416 hw/bus/spi_hal: Make cs pin optional
  hw/bus/drivers/spi_hal/src/spi_hal.c
Labels: size/s

#3412 hw/drivers/hash_stm32: Enable for STM32H devices
  hw/drivers/hash/hash_stm32/src/hash_stm32.c
Labels: size/xs

#3420 log_console: Append new line if not present
  sys/log/full/src/log_console.c
Labels: size/xs

#3418 bus/spi_stm32: Fix spi initialization sequence
  hw/bus/drivers/spi_stm32/src/spi_stm32.c
Labels: size/xs

#3421 stm32/hal_uart: Enable FIFO if present
  hw/mcu/stm/stm32_common/src/hal_uart.c
Labels: STM, size/xs

#3419 bus: Allow configuration change for a node
  hw/bus/drivers/i2c_common/include/bus/drivers/i2c_common.h
  hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c
  hw/bus/drivers/i2c_hal/src/i2c_hal.c
  hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c
  hw/bus/drivers/i2c_nrf5340/src/i2c_nrf5340.c
  hw/bus/drivers/i2c_nrf91_twim/src/i2c_nrf91_twim.c
  hw/bus/drivers/spi_apollo3/src/spi_apollo3.c
  hw/bus/drivers/spi_common/include/bus/drivers/spi_common.h
  hw/bus/drivers/spi_da1469x/src/spi_da1469x.c
  hw/bus/drivers/spi_hal/src/spi_hal.c
  hw/bus/drivers/spi_stm32/src/spi_stm32.c
  hw/bus/src/bus.c
Labels: size/s
