Repository apache/mynewt-core, pull requests merged in 2025-04, with the labels that each got.

#3407 hw/stm32gx: Remove incorrect syscfg values
  hw/bsp/nucleo-g0b1re/syscfg.yml
  hw/bsp/nucleo-g491re/syscfg.yml
  hw/bsp/weact_g431cb/syscfg.yml
Labels: STM, BSP, size/xs

#3404 hw/stm32u5: Fix clock settings
  hw/bsp/nucleo-u575zi-q/syscfg.yml
  hw/mcu/stm/stm32u5xx/src/clock_stm32u5xx.c
  hw/mcu/stm/stm32u5xx/syscfg.yml
Labels: STM, BSP, size/s

#3397 boot/startup: Increase interrupt stack in bootloader
  boot/startup/syscfg.yml
Labels: size/xs

#3405 tinyusb/msc_fat_view: Add entry for BOOT.BIN
  hw/usb/tinyusb/msc_fat_view/pkg.yml
  hw/usb/tinyusb/msc_fat_view/src/entry_boot_bin.c
  hw/usb/tinyusb/msc_fat_view/syscfg.yml
Labels: USB, size/s

#3402 hw/bsp/nucleo-l073rz: Remove duplicate syscfg.defs
  hw/bsp/nucleo-l073rz/syscfg.yml
Labels: STM, BSP, size/xs

#3408 log_console: Add option to print time stamp as clock time
  sys/log/full/pkg.yml
  sys/log/full/src/log_console.c
  sys/log/full/syscfg.yml
Labels: size/s

#3393 boot/startup: Update generated linker script for newt size
  boot/startup/include/mynewt_config.ld.h
Labels: size/xs

#3398 boot/startup: Add optional stack fill in startup
  boot/startup/src/arch/cortex_m0/cortex_m0_startup.s
  boot/startup/src/arch/cortex_m3/cortex_m3_startup.s
  boot/startup/src/arch/cortex_m33/cortex_m33_startup.s
  boot/startup/src/arch/cortex_m4/cortex_m4_startup.s
  boot/startup/src/arch/cortex_m7/cortex_m7_startup.s
  boot/startup/syscfg.yml
Labels: size/s

#3413 sys/reboot_log: Fix crash on rotate
  sys/log/full/src/log_fcb.c
Labels: size/s
