Repository apache/mynewt-core, pull requests merged in 2025-07, with the labels that each got.

#3447 tinyusb/msc_fat_view: Fix missing include file
  hw/usb/tinyusb/msc_fat_view/src/entry_config.c
Labels: USB, size/xs

#3446 hw/drivers/i2s: Fix setting for bypass mode
  hw/drivers/i2s/i2s_nrfx/src/i2s_nrfx.c
Labels: size/s

#3455 bsp/native: Add linker script for link tables
  hw/bsp/native/bsp.yml
  hw/bsp/native/native.ld
Labels: BSP, size/m

#3451 util/scfg: Update for c++
  sys/config/include/config/config.h
  util/scfg/include/scfg/scfg.h
  util/scfg/src/scfg.c
Labels: size/s

#3450 ci: Add information about skipping style check
  .github/workflows/check_compliance.yml
Labels: CI, size/xs, workflows-update

#3462 bsp/native: Fix linker script for native build
  hw/bsp/native/native.ld
Labels: BSP, size/m

#3461 fs/littlefs: Fix open functions
  fs/littlefs/src/mynewt_glue.c
Labels: size/xs

#3468 hw/scripts: Add adapter selection for opencod
  hw/scripts/openocd.sh
Labels: size/s

#3473 hw/drivers/da1469x_charger: Fix prototype mismatch
  hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger.c
Labels: size/xs

#3478 hw/mcu: Add watchdog support for apollo3 with configurable clock
  hw/bsp/apollo3_evb/syscfg.yml
  hw/mcu/ambiq/apollo3/src/hal_watchdog.c
Labels: BSP, size/s

#3471 hw/mcu: add reset cause handling for apollo2 board
  hw/mcu/ambiq/apollo2/src/hal_system.c
Labels: size/s

#3479 boot/startup: Fix alignment for relocate vectors
  boot/startup/mynewt_cortex_m3.ld
  boot/startup/mynewt_cortex_m33.ld
  boot/startup/mynewt_cortex_m4.ld
  boot/startup/mynewt_cortex_m7.ld
Labels: size/xs

#3481 sys/shell: Fix help and select commands
  sys/shell/src/shell.c
Labels: size/xs

#3482 spiflash: Add dependency to stats when needed
  hw/drivers/flash/spiflash/pkg.yml
Labels: Trivial, size/xs

#3483 sys/log/shell: Fix string log shell printf for log entries with a trailer
  sys/log/full/include/log/log.h
  sys/log/full/src/log_shell.c
Labels: size/s

#3484 hw/mcu: add missing includes for __BKPT() and integer types
  hw/mcu/atmel/samd21xx/include/mcu/mcu.h
Labels: size/xs
