Repository apache/mynewt-core, pull requests merged in 2025-06, with the labels that each got.

#3425 hw/battery: Add missing dependency to adc
  hw/battery/pkg.yml
Labels: size/xs

#3430 log/full: Fix log level unit test
  sys/log/full/selftest/util/src/testcases/log_test_case_level.c
Labels: size/s

#3433 config: Cleanup config file initialization
  sys/config/include/config/config_file.h
  sys/config/src/config_file.c
  sys/config/src/config_init.c
  sys/config/syscfg.yml
Labels: size/s

#3437 fs/fatfs: Fix open for write
  fs/fatfs/src/mynewt_glue.c
Labels: size/xs

#3435 kernel/os: Fix msys unit tests
  kernel/os/selftest/src/msys_test.c
Labels: size/xs

#3438 bsp/pca10121: Init on board pins
  hw/bsp/nordic_pca10121/include/bsp/bsp.h
Labels: Nordic, BSP, size/xs

#3439 ci: Add workflows up-to-date check
  .github/workflows/check_workflows.yml
Labels: CI, size/s

#3432 Improve clang-format handling for macros and enums
  .clang-format
Labels: size/xs

#3434 tinyusb/msc_fat_view: Small fixes
  hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
  hw/usb/tinyusb/msc_fat_view/syscfg.yml
Labels: USB, size/m

#3400 sys/log, fs/fcb: Add support for trailers per entry in logs for fcb
  hw/mcu/native/src/hal_flash.c
  sys/log/full/include/log/log.h
  sys/log/full/selftest/util/src/testcases/log_test_case_2logs.c
  sys/log/full/selftest/util/src/testcases/log_test_case_append_cb.c
  sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_append_body.c
  sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_append_mbuf.c
  sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_append_mbuf_body.c
  sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_printf.c
  sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append.c
  sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append_body.c
  sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append_mbuf.c
  sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append_mbuf_body.c
  sys/log/full/selftest/util/src/testcases/log_test_case_fcb_printf.c
  sys/log/full/src/log.c
  sys/log/full/src/log_fcb.c
  sys/log/full/syscfg.yml
Labels: feature, LOGS, size/l
